name: multi-task-learning
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.12.0+cu113
  - torchaudio=0.12.0+cu113
  - torchvision=0.13.0+cu113
  - cudatoolkit=11.4
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
