name: multi-task-learning
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.4
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
